version: '3.8'
services:
    postgres:
        container_name: BookingEventDB_Cont
        image: postgres
        hostname: localhost
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: rootDB
            POSTGRES_PASSWORD: root1234
            POSTGRES_DB: BookingEventDB_db
        volumes:
            - BookingEventDB_VOL:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        container_name: container-pgadmin
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        restart: unless-stopped

volumes:
    BookingEventDB_VOL:
